### ISSUE TITLE
[text-to-speech] INVALID_ARGUMENT: Empty language code.

### ISSUE THREAD

**Issue by MoeMaher** [GoogleCloudPlatform/firebase-extensions#100]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: text-to-speech
- Extension version: 0.1.3
- Configuration values (redact info where appropriate):
![image](https://github.com/GoogleCloudPlatform/firebase-extensions/assets/36363274/632a4b09-bfd7-4300-b767-d937b448b19b)

#### Steps to reproduce:
- installed the extension with the configurations in the image attached.
- then added a document to the "script" collection.
- There is no other extensions installed or other functions
- I also tried enabling and disabling per document overrides.

##### Expected result
I expect to find the audio file generated in the specified folder
##### Actual result
nothing happens, I also saw the logs for the extension's cloud function and found there is an error as follows 
Error: 3 INVALID_ARGUMENT: Empty language code.
    at callErrorFromStatus (/workspace/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /workspace/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)

here is a screenshot of the error 
![image](https://github.com/GoogleCloudPlatform/firebase-extensions/assets/36363274/2e295ac6-86dd-47c0-89a6-0479f2091a57)

**Comment by dackers86** [comment]
Related to: https://github.com/GoogleCloudPlatform/firebase-extensions/issues/99
