### ISSUE TITLE
The Transcribe Speech to Text extension is not working locally

### ISSUE THREAD

**Issue by umaar** [GoogleCloudPlatform/firebase-extensions#105]
When running this extension locally, it doesn't work. It appears to fail at the `ffmpeg` step.

- Extension name: **speech-to-text**
- Extension version: **0.1.3**
- Configuration values:

```
EXTENSION_BUCKET=demo-codelab-test-1.appspot.com
LANGUAGE_CODE=en-GB
LOCATION=europe-west2
MODEL=default
OUTPUT_STORAGE_PATH=stt
```

This extension doesn't appear to work in a local Firebase `demo` project. When running this locally, I believe `ffmpeg` is run [locally](https://github.com/GoogleCloudPlatform/firebase-extensions/blob/next/speech-to-text/functions/src/transcribe-audio.ts#L228). The errors seem to be related to that.

Note, I do have `ffmpeg` installed locally. The errors look like this:

```
>  {"config":{"bucket":"demo-codelab-test-1.appspot.com","languageCode":"en-GB","model":"default","outputStoragePath":"stt"},"severity":"INFO","message":"Initializing extension with configuration"}
i  functions: Beginning execution of "europe-west2-ext-speech-to-text-transcribeAudio"
>  {"config":{"bucket":"demo-codelab-test-1.appspot.com","languageCode":"en-GB","model":"default","outputStoragePath":"stt"},"severity":"INFO","message":"Started execution of extension with configuration"}
>  {"severity":"INFO","message":"Creating temporary directory: '/var/folders/hr/5krc94l55q35t4nkr95h2g9r0000gn/T'"}
>  {"severity":"INFO","message":"Created temporary directory: '/var/folders/hr/5krc94l55q35t4nkr95h2g9r0000gn/T'"}
>  {"severity":"INFO","message":"Downloading audio from 'c0d794f8-d79e-4fa6-8fbd-ff79dc3d876b-foo.wav'"}
>  {"severity":"INFO","message":"Downloaded audio from 'c0d794f8-d79e-4fa6-8fbd-ff79dc3d876b-foo.wav' to '/var/folders/hr/5krc94l55q35t4nkr95h2g9r0000gn/T/c0d794f8-d79e-4fa6-8fbd-ff79dc3d876b-foo.wav'"}
>  {"streams":[{"index":0,"codec_name":"pcm_s16le","codec_long_name":"PCM signed 16-bit little-endian","profile":"unknown","codec_type":"audio","codec_tag_string":"[1][0][0][0]","codec_tag":"0x0001","sample_fmt":"s16","sample_rate":16000,"channels":1,"channel_layout":"unknown","bits_per_sample":16,"initial_padding":0,"id":"N/A","r_frame_rate":"0/0","avg_frame_rate":"0/0","time_base":"1/16000","start_pts":"N/A","start_time":"N/A","duration_ts":325476,"duration":20.34225,"bit_rate":256000,"max_bit_rate":"N/A","bits_per_raw_sample":"N/A","nb_frames":"N/A","nb_read_frames":"N/A","nb_read_packets":"N/A","disposition":{"default":0,"dub":0,"original":0,"comment":0,"lyrics":0,"karaoke":0,"forced":0,"hearing_impaired":0,"visual_impaired":0,"clean_effects":0,"attached_pic":0,"timed_thumbnails":0,"captions":0,"descriptions":0,"metadata":0,"dependent":0,"still_image":0}}],"format":{"filename":"/var/folders/hr/5krc94l55q35t4nkr95h2g9r0000gn/T/c0d794f8-d79e-4fa6-8fbd-ff79dc3d876b-foo.wav","nb_streams":1,"nb_programs":0,"format_name":"wav","format_long_name":"WAV / WAVE (Waveform Audio)","start_time":"N/A","duration":20.34225,"size":650996,"bit_rate":256017,"probe_score":99},"chapters":[],"severity":"INFO","message":"probe data before transcription:"}
>  {"severity":"INFO","message":"transcoding locally"}
>  ----------------------------
>  inputPath /var/folders/hr/5krc94l55q35t4nkr95h2g9r0000gn/T/c0d794f8-d79e-4fa6-8fbd-ff79dc3d876b-foo.wav
>  outputPath /var/folders/hr/5krc94l55q35t4nkr95h2g9r0000gn/T/c0d794f8-d79e-4fa6-8fbd-ff79dc3d876b-foo.wav.wav
>  ----------------------------
>  {"severity":"INFO","message":"finished transcoding locally"}
>  {"severity":"INFO","message":"uploading transcoded file"}
>  {"severity":"INFO","message":"uploaded transcoded file"}
>  {"config":{"bucket":"demo-codelab-test-1.appspot.com","languageCode":"en-GB","model":"default","outputStoragePath":"stt"},"severity":"INFO","message":"Initializing extension with configuration"}
>  {"severity":"ERROR","message":"Error: Error when transcribing audio\n    at entryFromArgs (/Users/me/.cache/firebase/extensions/googlecloud/speech-to-text@0.1.3/functions/node_modules/firebase-functions/lib/logger/index.js:130:19)\n    at Object.error (/Users/me/.cache/firebase/extensions/googlecloud/speech-to-text@0.1.3/functions/node_modules/firebase-functions/lib/logger/index.js:116:11)\n    at Object.error (/Users/me/.cache/firebase/extensions/googlecloud/speech-to-text@0.1.3/functions/lib/logs.js:23:33)\n    at /Users/me/.cache/firebase/extensions/googlecloud/speech-to-text@0.1.3/functions/lib/index.js:120:14\n    at async runFunction (/Users/me/.npm-global/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:506:9)\n    at async runBackground (/Users/me/.npm-global/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:517:5)\n    at async processBackground (/Users/me/.npm-global/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:501:5)\n    at async /Users/me/.npm-global/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:689:21"}
>  {"severity":"ERROR","message":"Error: 5 NOT_FOUND: Requested entity was not found.\n    at callErrorFromStatus (/Users/me/.cache/firebase/extensions/googlecloud/speech-to-text@0.1.3/functions/node_modules/@grpc/grpc-js/build/src/call.js:31:19)\n    at Object.onReceiveStatus (/Users/me/.cache/firebase/extensions/googlecloud/speech-to-text@0.1.3/functions/node_modules/@grpc/grpc-js/build/src/client.js:192:76)\n    at Object.onReceiveStatus (/Users/me/.cache/firebase/extensions/googlecloud/speech-to-text@0.1.3/functions/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)\n    at Object.onReceiveStatus (/Users/me/.cache/firebase/extensions/googlecloud/speech-to-text@0.1.3/functions/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)\n    at /Users/me/.cache/firebase/extensions/googlecloud/speech-to-text@0.1.3/functions/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)\nfor call at\n    at ServiceClientImpl.makeUnaryRequest (/Users/me/.cache/firebase/extensions/googlecloud/speech-to-text@0.1.3/functions/node_modules/@grpc/grpc-js/build/src/client.js:160:34)\n    at ServiceClientImpl.<anonymous> (/Users/me/.cache/firebase/extensions/googlecloud/speech-to-text@0.1.3/functions/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)\n    at /Users/me/.cache/firebase/extensions/googlecloud/speech-to-text@0.1.3/functions/node_modules/@google-cloud/speech/build/src/v1/speech_client.js:230:29\n    at /Users/me/.cache/firebase/extensions/googlecloud/speech-to-text@0.1.3/functions/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16\n    at LongrunningApiCaller._wrapOperation (/Users/me/.cache/firebase/extensions/googlecloud/speech-to-text@0.1.3/functions/node_modules/google-gax/build/src/longRunningCalls/longRunningApiCaller.js:55:16)\n    at /Users/me/.cache/firebase/extensions/googlecloud/speech-to-text@0.1.3/functions/node_modules/google-gax/build/src/longRunningCalls/longRunningApiCaller.js:46:25\n    at OngoingCallPromise.call (/Users/me/.cache/firebase/extensions/googlecloud/speech-to-text@0.1.3/functions/node_modules/google-gax/build/src/call.js:67:27)\n    at LongrunningApiCaller.call (/Users/me/.cache/firebase/extensions/googlecloud/speech-to-text@0.1.3/functions/node_modules/google-gax/build/src/longRunningCalls/longRunningApiCaller.js:45:19)\n    at /Users/me/.cache/firebase/extensions/googlecloud/speech-to-text@0.1.3/functions/node_modules/google-gax/build/src/createApiCall.js:84:30\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {\n  code: 5,\n  details: 'Requested entity was not found.',\n  metadata: Metadata {\n    internalRepr: Map(2) {\n      'endpoint-load-metrics-bin' => [Array],\n      'grpc-server-stats-bin' => [Array]\n    },\n    options: {}\n  }\n}"}
i  functions: Finished "europe-west2-ext-speech-to-text-transcribeAudio" in 1755.571708ms
```

Using macOS. `ffmpeg -version` shows:

```
 ➜ ffmpeg -version
ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers
built with Apple clang version 14.0.3 (clang-1403.0.22.14.1)
configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/6.0 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-neon
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100
```

**Comment by dackers86** [comment]
Hi @umaar 

I also had this issue developing locally, `ffmpeg` is already installed on the Firebase Cloud Function Runtime, see a nice article from [Fireship](https://fireship.io/lessons/ffmpeg-useful-techniques/#:~:text=FFmpeg%20is%20available%20in%20the,js.) on this.

This dependency would need to be installed locally for local development.

**Comment by dackers86** [comment]
Closing as solution provided.

**Comment by umaar** [comment]
Thank for the response. But note `ffmpeg` was already installed - in the original bug report I shared the output to confirm it was already installed.
