### ISSUE TITLE
[firestore-semantic-search] update_index_config.js error: metdata.data is undefined

### ISSUE THREAD

**Issue by AlexZhidkov** [GoogleCloudPlatform/firebase-extensions#283]
### [READ] Step 1: Are you in the right place?
Yes.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **firebase-semantic-search**
- Extension version: **0.1.7**
- Configuration values (redact info where appropriate):
Collection to index: activities
Fields in a Document to index (Optional): title
Do backfill?: true
Embeddings method: palm
PaLM embeddings model (Optional): Parameter not set
Distance measure type: DOT_PRODUCT_DISTANCE
Algorithm config: bruteForceConfig
Approximate number of neighbors: 50
Shard size: SHARD_SIZE_SMALL
Machine type (Optional): e2-standard-2
Acceletaor type (Optional): ACCELERATOR_TYPE_UNSPECIFIED
Accelerator Count (Optional): 1
Min replica count (Optional): 1
Max replica count (Optional): 1
Cloud Functions location: australia-southeast1

### [REQUIRED] Step 3: Describe the problem
When trying to make any call to `ext-firestore-semantic-search-queryIndex`, such as
`gcloud functions --project screenhush call ext-firestore-semantic-search-queryIndex --data '{"data": {"query":["park"]}}'`
Getting the following error:
`
TypeError: Cannot destructure property 'index' of 'metdata.data(...)' as it is undefined.
    at updateIndexConfigHandler (/workspace/lib/functions/update_index_config.js:29:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
`
#### Steps to reproduce:
Execute `gcloud functions --project screenhush call ext-firestore-semantic-search-queryIndex --data '{"data": {"query":["park"]}}'`

##### Expected result
Response status 200

##### Actual result
Response status 500
`TypeError: Cannot destructure property 'index' of 'metdata.data(...)' as it is undefined.
    at updateIndexConfigHandler (/workspace/lib/functions/update_index_config.js:29:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
`

**Comment by AlexZhidkov** [comment]
It's been 6 hours since I installed the extension and it still shows `status: "PENDING"`
![image](https://github.com/GoogleCloudPlatform/firebase-extensions/assets/8213739/506dc9ac-8094-479d-8bd6-da18f154d544)

**Comment by AlexZhidkov** [comment]
It's been 24 hours since I've installed the extension now and nothing has changed. I've tried reinstalling it but it didn't help. How can I debug this to see what is the problem?

**Comment by cabljac** [comment]
I'm going to close this as stale as it involves the PaLM models. if this is happening with newer models i'll open a fresh issue to track. Thanks!
