### ISSUE TITLE
[firestore-genai-chatbot]: strange error (may be filters not handled correctly)

### ISSUE THREAD

**Issue by cabljac** [GoogleCloudPlatform/firebase-extensions#387]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **firestore-genai-chatbot**

#### Steps to reproduce:

1. install extension with overrides on and a nested COLLECTION_NAME/COLLECTION_PATH param
2. add context "you are a pirate" to the parent doc
3. add the first prompt "hello"

This results in the following error:

<img width="1279" alt="Screenshot 2024-02-26 at 08 53 15" src="https://github.com/GoogleCloudPlatform/firebase-extensions/assets/32874567/2723df0e-d36a-4c45-ba4e-1ce2b9f79509">

What happened? How can we make the problem occur?
This could be a description, [log/console output](https://firebase.google.com/docs/extensions/manage-installed-extensions#view-logs), etc.

**Comment by MrDariusAD** [comment]
I also have this issue for some days now. I also tried to adjust my context but it didn't help. My logs look like this: 

`ClientError: [VertexAI.ClientError]: got status: 400 Bad Request
    at throwErrorIfNotOK (/workspace/node_modules/@google-cloud/vertexai/build/src/index.js:395:15)
    at GenerativeModel.generateContentStream (/workspace/node_modules/@google-cloud/vertexai/build/src/index.js:321:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async VertexDiscussionClient.generateResponse (/workspace/lib/generative-client/vertex_ai.js:54:36)
    at async VertexDiscussionClient.send (/workspace/lib/generative-client/base_class.js:26:16)
    at async FirestoreOnWriteProcessor.generateChatResponse [as processFn] (/workspace/lib/generate_chat_response.js:25:20)
    at async FirestoreOnWriteProcessor.run (/workspace/lib/firestore-onwrite-processor/index.js:83:28) {
  stack_trace: undefined
}`

**Comment by cabljac** [comment]
Thanks for the extra context. I'll investigate and get back to you with updates.

**Comment by cabljac** [comment]
Unable to reproduce this recently after multiple attempts, closing for now (will reopen if this ever reoccurs)
