### ISSUE TITLE
Incremental backups - Task Size too large

### ISSUE THREAD

**Issue by zdhernandez** [GoogleCloudPlatform/firebase-extensions#607]
What is causing this error ?

ext-firestore-incremental-capture-75po-syncData

Error: Task size too large
    at FunctionsApiClient.toFirebaseError (/workspace/node_modules/firebase-admin/lib/functions/functions-api-client-internal.js:305:16)
    at FunctionsApiClient.enqueue (/workspace/node_modules/firebase-admin/lib/functions/functions-api-client-internal.js:146:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by cabljac** [comment]
Hi there, thanks for raising this. I've seen a similar issue where Cloud Task payload size is a restriction. Basically firestore documents can be large enough to be over the limit of a Cloud Task payload.

I've marked this issue for investigation and will provide updates when available.

**Comment by cabljac** [comment]
Without a full re-architecture of the extension, this is out of scope for us to fix in this repository currently. I think the best we can do is to document the limitation clearly, to avoid confusion in the future.
